{{ $ingress := .Values.ingress }}
{{ if $ingress.enabled }}
{{ $serviceName := include "mattermost-team-edition.name" . }}
{{ $servicePort := .Values.service.externalPort }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "mattermost-team-edition.fullname" . }}
  labels:
    chart: {{ template "mattermost-team-edition.chart" . }}
    app: {{ template "mattermost-team-edition.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- toYaml $ingress.annotations | nindent 4 }}
spec:
  rules:
  {{- range $host := $ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: {{ $ingress.path }}
        backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ $servicePort }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- $ingress.tls | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
